apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: template-service-go
  annotations:
    github.com/project-slug: madeiramadeirabr/template-service-go
    backstage.io/techdocs-ref: dir:.
  tags:
    - go
    - python
    - shell
    - dockerfile
spec:
  type: template
  lifecycle: production
  owner: team-platform-engineering-admin
  
