version: "3.7"

services:
  # Application
  go-service-template:
    build:
      context: .
      dockerfile: cmd/go_service_template/Dockerfile
      target: development
    ports:
      - 8080:8080
    volumes:
      - .:/app
