root = "."
tmp_dir = "tmp"

[build]
  bin = "/tmp/go-service-template"
  cmd = "go build -o /tmp/go-service-template ./cmd/go-service-template"
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor"]
  exclude_file = []
  exclude_regex = []
  exclude_unchanged = false
  follow_symlink = true
  full_bin = ""
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "conf"]
  kill_delay = "0s"
  log = "go-service-template.log"
  send_interrupt = false
  stop_on_error = true

[color]
  app = "go-service-template"
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = true

[misc]
  clean_on_exit = false